title: "Kizy AI - An opinionated framework for diffusion based workflows"
date: "2025-12-15"
description: "A rough draft of the initial problem space is here: https://blog.kizy.cloud/hypothesis"
tags: ["comfyui", "stable-diffusion", "diffusion-models", "artificial-intelligence", "ai"]
draft: false
