title: "Building a chat system with Flutter and Cloud Firestore"
date: "2020-01-31"
description: "How to build a chat system in flutter under 20 minutes"
tags: ["flutter", "cloud-firestore", "mobile-chat-application", "firebase", "tutorial"]
draft: false
