title: "How to tame your LLM"
date: "2026-05-16"
description: "LLMs are intelligent beasts. Think of them as unicorns. Channel their powers"
tags: ["model-context-protocol", "langgraph", "anthropic-claude", "ai-assistant", "machine-learning-ai"]
draft: true
