title: "Creating an embeddable chatbot"
date: "2025-01-28"
description: "Creating and deploying a RAG-based chatbot for Question Answering over website content"
tags: ["langgraph", "ai-assistant", "chatbots-for-business", "artificial-intelligence", "ai"]
draft: false
