title: "SDLC Skill for Claude"
date: "2025-12-21"
description: "Automate your development (Meeting Transcript -> SDLC Skill -> PRD + HLD + EIS -> Code)"
tags: ["claude-code", "sdlc", "autonomous-coding", "artificial-intelligence", "ai"]
draft: false
